## scripts for summarising overall important features ## 

setwd("")


library(sjPlot)

# Data summary (source data for Fig8A) is generated using information of the SHAP values stored in files written out by : generated by: XGBoost_cleaned.R
#write.table(combined_raw_values,"SHAP_values_CV5_testset.txt", row.names = F, quote = F, sep = "\t")
#write.table(combined_shap_values,"SHAP_raw_data_values_CV5_testset.txt", row.names = F, quote = F, sep = "\t")

shap_long = shap.prep(shap = shap_results,
                      X_train = combined_raw_values,
                      top_n =length(which(shap_results$mean_shap_score > 0)))

write.table(as.data.frame(table(shap_long$variable)),"SourceData_Fig8A_Arm.txt",
            row.names = F, col.names = T, quote = F, sep = "\t")



##### Load data #############
## make ranked table ##
Arm <- read.table("SourceData_Fig8A_Arm.txt", header = T, sep = "\t")
Arm <- Arm[1:15,1]

Foot <- read.table("SourceData_Fig8A_Foot.txt", header = T, sep = "\t")
Foot <- Foot[1:15,1]

Spine <- read.table("SourceData_Fig8A_Spine.txt", header = T, sep = "\t")
Spine <- Spine[1:15,1]

Hip <- read.table("SourceData_Fig8A_Hip.txt", header = T, sep = "\t")
Hip <- Hip[1:15,1]

Knee <- read.table("SourceData_Fig8A_Knee.txt", header = T, sep = "\t")
Knee <- Knee[1:15,1]

combined <- data.frame(Arm,Foot,Spine,Hip,Knee)
combined$Rank <- seq(from=1, to= 15, by = 1)
tab_df(combined)




